version: "3.8"

services:
  app1:
    image: python:3.10-slim
    container_name: app1
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "pip install flask && python app.py"

  app2:
    image: python:3.10-slim
    container_name: app2
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "pip install flask && python app.py"

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
